apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: tf-ressources
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  path: ./tf
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  backendConfig:
    secretSuffix: localstack
